{{- if .Values.managerRbac.create }}
# This contains the serviceAccount used for the traffic-manager deployment.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-manager
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}

{{- end }}
